services:
  flight-price-api:
    build: .
    container_name: flight-price-api
    environment:
      APP_ENV: development
      SERVER_PORT: 8443
      CLIENT_TIMEOUT: 10s
      AMADEUS_BASE_URL: https://test.api.amadeus.com
      AMADEUS_API_KEY: /run/secrets/amadeus_api_key
      AMADEUS_API_SECRET: /run/secrets/amadeus_api_secret
      SKYSCANNER_API_KEY: /run/secrets/skyscanner_api_key
      GOOGLE_FLIGHTS_API_KEY: /run/secrets/google_flights_api_key
      SKYSCANNER_BASE_URL: https://flights-sky.p.rapidapi.com
      APP_BASE_URL: https://domain
    secrets:
      - amadeus_api_key
      - amadeus_api_secret
      - skyscanner_api_key
      - google_flights_api_key
    ports:
      - "8443:8443"

secrets:
  amadeus_api_key:
    file: ./secrets/amadeus_api_key.txt
  amadeus_api_secret:
    file: ./secrets/amadeus_api_secret.txt
  skyscanner_api_key:
    file: ./secrets/sky_rapid_api_key.txt
  google_flights_api_key:
    file: ./secrets/flight_rapid_api_key.txt