services:
  flight-price-api:
    build: .
    container_name: flight-price-api
    environment:
      APP_ENV: development
      SERVER_PORT: 8443
      CLIENT_TIMEOUT: 10s
      AMADEUS_API_KEY: amadeus_api_key
      AMADEUS_API_SECRET: amadeus_api_secret
      SKY_RAPID_API_KEY: sky_rapid_api_key
      GOOGLE_FLIGHT_RAPID_API_KEY: google_flight_rapid_api_key
      AMADEUS_BASE_URL: https://test.api.amadeus.com
      SKY_RAPID_BASE_URL: https://flights-sky.p.rapidapi.com
      GOOGLE_FLIGHT_RAPID_BASE_URL: https://google-flights4.p.rapidapi.com
      APP_BASE_URL: https://domain
    secrets:
      - amadeus_api_key
      - amadeus_api_secret
      - sky_rapid_api_key
      - google_flight_rapid_api_key
    ports:
      - "8443:8443"

secrets:
  amadeus_api_key:
    file: secrets/amadeus_api_key.txt
  amadeus_api_secret:
    file: secrets/amadeus_api_secret.txt
  sky_rapid_api_key:
    file: secrets/sky_rapid_api_key.txt
  google_flight_rapid_api_key:
    file: secrets/google_flight_rapid_api_key.txt